# Generated by Django 5.2.1 on 2025-05-23 14:20

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.CharField(help_text='رقم الطالب يجب أن يكون فريدًا', max_length=10, unique=True, verbose_name='رقم الطالب')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('E', 'Evaluator'), ('S', 'Student'), ('V', 'Visitor')], default='S', max_length=1)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='رقم الهاتف')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('presentation_time', models.DateTimeField(default=datetime.datetime(2025, 5, 30, 14, 20, 40, 584275, tzinfo=datetime.timezone.utc), verbose_name='موعد العرض')),
                ('location', models.CharField(default='قاعة المناقشة', max_length=100, verbose_name='مكان العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='التقييم')),
                ('comments', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_evaluations', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.project', verbose_name='المشروع'),
        ),
    ]
