# Generated by Django 5.2.1 on 2025-05-23 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='presentation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 14, 20, 43, 27758, tzinfo=datetime.timezone.utc), verbose_name='موعد العرض'),
        ),
    ]
