# Generated by Django 5.2.1 on 2025-05-23 14:40

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_presentation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='يجب أن يكون الملف بصيغة PDF', null=True, upload_to=core.models.project_file_path, verbose_name='ملف المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='presentation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 14, 40, 19, 80464, tzinfo=datetime.timezone.utc), verbose_name='موعد العرض'),
        ),
    ]
